#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml
app_camera_capture:
    path: '/camera/capture'
    controller: 'App\Controller\CameraController::capture'
    methods: ['GET', 'POST']
